let public
    SRPITE_ROOT: string = "assets/sprites/"

    TILES: string = SRPITE_ROOT + "tiles/tiles.png"

    PLAYER: string = SRPITE_ROOT + "characters/player.png"

    TORCHES: string = SRPITE_ROOT + "objects/torches.png"

    TITLE_SCREEN: string = SRPITE_ROOT + "title_screen.png"
    
    BUTTON_START: string = SRPITE_ROOT + "button_start.png"

    BUTTON_EXIT: string = SRPITE_ROOT + "button_exit.png"