let public
    TILES: string = "assets/sprites/tiles/tiles.png"

    PLAYER: string = "assets/sprites/characters/player.png"

    CHARACTER_SHADOW: string = "assets/sprites/characters/regular_character_shadow.png"

    TORCHES: string = "assets/sprites/objects/torches.png"

    TITLE_SCREEN: string = "assets/sprites/title_screen.png"
    
    BUTTON_START: string = "assets/sprites/button_start.png"

    BUTTON_EXIT: string = "assets/sprites/button_exit.png"